include("$(MPY_DIR)/extmod/uasyncio/manifest.py")
#freeze ("$(MPY_LIB_DIR)/", "bno055.py")
#freeze ("$(MPY_LIB_DIR)/", "modbus.py")
#freeze ("$(MPY_LIB_DIR)/", "mqtt.py")
#freeze ("$(MPY_LIB_DIR)/", "mutex.py")
#freeze ("$(MPY_LIB_DIR)/", "pid.py")
#freeze ("$(MPY_LIB_DIR)/", "rpc.py")
#freeze ("$(MPY_LIB_DIR)/", "rtsp.py")
#freeze ("$(MPY_LIB_DIR)/", "ssd1306.py")
#freeze ("$(MPY_LIB_DIR)/", "tb6612.py")
#freeze ("$(MPY_LIB_DIR)/", "vl53l1x.py")
freeze ("$(MPY_LIB_DIR)/", "astro_sensor.py")
freeze ("$(MPY_LIB_DIR)/", "blobstar.py")
freeze ("$(MPY_LIB_DIR)/", "captive_portal.py")
freeze ("$(MPY_LIB_DIR)/", "comutils.py")
freeze ("$(MPY_LIB_DIR)/", "exclogger.py")
freeze ("$(MPY_LIB_DIR)/", "star_finder.py")
freeze ("$(MPY_LIB_DIR)/", "time_location.py")
